// <auto-generated />
using Budalapi.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Budalapi.Migrations
{
    [DbContext(typeof(BudalapiContext))]
    partial class BudalapiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Budalapi.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CountryId");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Budalapi.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ISO1366_Alpha2")
                        .HasMaxLength(3);

                    b.Property<string>("Name")
                        .HasMaxLength(11);

                    b.Property<int>("PhoneCode");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Budalapi.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CityId");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("District");
                });
#pragma warning restore 612, 618
        }
    }
}
